name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - "Backend/**"
    paths-ignore:
      - "**.md"
      - ".github/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/JIRA-BOT
            git pull origin main
            cd Backend
            npm install
            npm run build
            pm2 restart backend
